/**:
  ros__parameters:
    #camra_param
    cam_mode: video_cam   #realsense #or #video_cam  
    cam_num : 1 #or2

    #debug_mode
    debug : True

    #detect tools 
    detect_mode : Object_detect # or #Instance_Segmentation　
    
    #ros2_topic
    image_topic : /camera/color/image_raw
    depth_topic : /camera/depth/image_rect_raw
    seg_topic : /SegInfo
    camera_info_topic : /wamv/sensors/cameras/ball_shooter_camera_sensor/optical/camera_info
    
